### ISSUE TITLE
Is it possible to write artists from "Featuring" for each track?

### ISSUE THREAD

**Issue by pcroland** [ghDaYuYu/foo_discogger#103]

**Comment by ghuDaYuYu** [comment]
Please provide a release Id for testing.
DISCOGS_CREDIT_FEATURING should provide "Featuring" for each track.

**Comment by pcroland** [comment]
https://www.discogs.com/release/7881774-Furakor-AKR-Fura

**Comment by ghuDaYuYu** [comment]
It worked here adding DISCOGS_CREDIT_FEATURING to the tag mapping (Tag Mapping panel->Add tag... ->Notes & Credits-> DISCOGS_CREDIT_FEATURING), then setting its action to Write.
What have you tried so far?


![Featuring](https://github.com/ghDaYuYu/foo_discogger/assets/62167612/df859131-56c5-4086-ad42-76da0aa47749)

**Comment by pcroland** [comment]
Is it possible to add them into the Artists value instead of `DISCOGS_CREDIT_FEATURING`? I would like Navidrome to show them so the library is better explorable.

**Comment by ghuDaYuYu** [comment]
I see... You may try the following Artist definition, it joins both artist and featuring artists for each track:

`$split($if($join($joinnames(%<ARTISTS_NAME>%,%<ARTISTS_JOIN>%)),$join($joinnames(%<ARTISTS_NAME>%,%<ARTISTS_JOIN>%))', ')$join($flatten($multi_if($any($multi_strcmp($sextend(%<<TRACK_CREDITS_SHORT_ROLES>>%,%<<RELEASE_CREDITS_SHORT_ROLES>>%),'Featuring')),$multi_if($put(aj,$sextend(%<<TRACK_CREDITS_ARTISTS_JOIN>>%,%<<RELEASE_CREDITS_ARTISTS_JOIN>>%)),$joinnames($put(an,$sextend(%<<TRACK_CREDITS_ARTISTS_NAME>>%,%<<RELEASE_CREDITS_ARTISTS_NAME>>%)),$get(aj)),$get(an)),))))`

**Comment by ghuDaYuYu** [comment]
Also here is another version, removing the artist join and duplicates, as the featuring artist may already be included as Artists:

`$unique($split($if($join($flatten(%<ARTISTS_NAME>%)),$join($flatten(%<ARTISTS_NAME>%))', ')$join($flatten($multi_if($any($multi_strcmp($sextend(%<<TRACK_CREDITS_SHORT_ROLES>>%,%<<RELEASE_CREDITS_SHORT_ROLES>>%),'Featuring')),$multi_if($put(aj,$sextend(%<<TRACK_CREDITS_ARTISTS_JOIN>>%,%<<RELEASE_CREDITS_ARTISTS_JOIN>>%)),$joinnames($put(an,$sextend(%<<TRACK_CREDITS_ARTISTS_NAME>>%,%<<RELEASE_CREDITS_ARTISTS_NAME>>%)),$get(aj)),$get(an)),)))))`

Hope it helps,
Regards

**Comment by ghuDaYuYu** [comment]
Closing issue as answered
