### ISSUE TITLE
Compilation: Artist should be used for search instead of Album Artist

### ISSUE THREAD

**Issue by bassstorm** [ghDaYuYu/foo_discogger#105]
**Use case:**
When I call Discogger for a compilation (albumartist = VA) I expect to see search results for its artist(s).

**Expected:**
Search by first artist (or something a bit more smarter) to have Album selection filter actually work.

**Actual:**
Search happens for "VA" with no meaningful results.

P.S. Same for "Various Artists" and "Various".
P.P.S. There's no configuration for that behavior in Searching tab either.

**Comment by ghuDaYuYu** [comment]
As a side note, the album selection filter should work for tracks containing 'Album Title'.
If the value is present and not displayed as the Find Release Filter, then there might be a bug initiating the dialog.

Just to clarify I understand the use case. The files already contain Album Title and track Artists.
And you'd like VA 'Album Artist' being ignored and look up the first track Artist instead, is that right?
If I am getting it right, that´s a pretty good idea!
Can´t tell when a new release will be available... but the feature is now in the todo list.

P.S.

Just wondering about a more elaborated solution...

Ideally, there should be either a check box modifying the search button behavior or a 'Search for releases' one that searches for releases containing multiple artists.

For instance (not a very good example, btw):
https://www.discogs.com/release/203071 features Radanna and Costanza.
Then, filling the Artist/URL search field with Radanna+Costanza and pressing 'Search releases' fetches and adds
'Back to Mine' among a few other releases to the Release Tree panel.

**Comment by bassstorm** [comment]
Yes, you get it right. Normally my files are more or less fully tagged, but lack extra information like label and catalog #. That's often true for compilation albums. I use "VA" as Album Artist for these, but raw files may have "Various Artists" or "Various" as well.

As for your example, yes, I would expect something like that (not sure on exact Discogs REST API capabilities tho). But also maybe the checkbox could be supplied with a little smartness, i.e. configurable _$if()_ switch which should produce that _true/false_ value for the checkbox.

**Comment by ghuDaYuYu** [comment]
Added to TODO list

**Comment by ghuDaYuYu** [comment]
Added to TODO list
