### ISSUE TITLE
Close popup window after writing tags

### ISSUE THREAD

**Issue by bassstorm** [ghDaYuYu/foo_discogger#106]
When tags are written, popup window stays open. I have to manually close it every time to proceed with next release, because otherwise "Write tags..." context menu is disabled.

![image](https://github.com/ghDaYuYu/foo_discogger/assets/749825/b69f1122-241f-4c14-980f-9180362301e1)

Is there any way to make that behavior a bit more handy? Say, close window automatically, or allow restarting search from the playlist.

Thanks!

**Comment by ghuDaYuYu** [comment]
Does the Find Release dialog remain open after pressing 'Write tags'?
Which 'Write tags' button was used?

**Comment by bassstorm** [comment]
That's how it looks after pressing "Write tags" button at the very last step (Preview Tags):
- tags applied
- "Write tags" button is disabled
- popup stays open

![image](https://github.com/ghDaYuYu/foo_discogger/assets/749825/52e820f0-30d5-4462-9c8b-7e41478995f1)

**Comment by ghuDaYuYu** [comment]
Disable 'Sticky preview panel' in the Tagging preferences.
A disabled Write tags button in the preview panel just means that pressing it will not perform any action.

**Comment by bassstorm** [comment]
Just double checked - it's disabled already here...
![image](https://github.com/ghDaYuYu/foo_discogger/assets/749825/5fcc1223-7352-4327-80ad-ac36055ba2e7)

**Comment by ghuDaYuYu** [comment]
> When tags are written, popup window stays open

Now pressing the 'Write tags' button in the Preview dialog should also close it.

**Comment by ghuDaYuYu** [comment]
Closed as nonreproducible

**Comment by bassstorm** [comment]
By the way, forgot to mention... this is foobar2000 2.0 x64 running under Linux/Wine. Might be related to why you cannot reproduce.

**Comment by ghuDaYuYu** [comment]
Oh... I was blind but now I see.
This release should fix it.
Note the 'sticky preview panel' only applies to the Write tags button,
not to the preview context menu operations.

Beta 2 also includes export/import tag mapping as JSON featured in the previous beta.

[foo_discogger - v1.0.20.beta.2.zip](https://github.com/ghDaYuYu/foo_discogger/files/12434255/foo_discogger.-.v1.0.20.beta.2)

**Comment by bassstorm** [comment]
Confirmed as fixed by beta2 release. Thanks a lot :bowing_man:
