### ISSUE TITLE
json parser error for album art

### ISSUE THREAD

**Issue by adriaon** [ghDaYuYu/foo_discogger#114]
Hi,

Updating album art fails for this one:

(skipped) Error [release 66554]: Error loading release 66554: JSON Parser ExceptionArray assertion failed.

Cheers.

**Comment by ghuDaYuYu** [comment]
Hi adrion, can´t repricate the error here...
what version are you running, v1.0.20.5 or earlier?

**Comment by adriaon** [comment]
Hi, sorry. Was confused with the old plugin. Cheers.
